GTKWAVE:=$(which gtkwave)

all: decoder

decoder:prerequisites decoder_2by4.cc
	@echo 'building file $(@F)'
	$(CXX) -I/usr/local/systemc-2.3.1/include -O0 -g3 -Wall -c decoder_2by4.cc
	$(CXX) -L/usr/local/systemc-2.3.1/lib-linux64 -o decoder decoder_2by4.o -lsystemc
	./decoder
	gtkwave -c 4 timing_diagram.vcd

prerequisites: 
ifneq "$(GTKWAVE)" "/usr/bin/gtkwave"
	@echo 'installing gtkwave, please wait.'
	sudo dnf install gtkwave
endif
.PHONY: decoder
